name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test SSH connection
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          echo "EC2_USER: $EC2_USER"
          echo "EC2_HOST: $EC2_HOST"
          echo "SSH_PRIVATE_KEY length: ${#SSH_PRIVATE_KEY}"
          # 直接將 base64 內容寫入並解碼
          echo "$SSH_PRIVATE_KEY" > private_key.b64
          base64 -d private_key.b64 > private_key
          chmod 600 private_key
          ssh -v -i private_key -o StrictHostKeyChecking=no "$EC2_USER@$EC2_HOST" "echo 'SSH connection successful'"
          rm -f private_key private_key.b64